spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 82


